[versions]
android-compileSdk = "32"
android-minSdk = "21"
android-tagetSdk = "32"

kotlin = "1.7.0"

dagger = "2.41"
compose = "1.1.0"

androidx-core = "1.7.0"
androidx-appcompat = "1.4.1"
androidx-lifecycle = "2.4.1"
androidx-activity = "1.4.0"
androidx-test = "1.1.3"
androidx-test-espresso = "3.4.0"
androidx-annotation = "1.3.0"
androidx-navigation = "2.4.1"
androix-paging = "3.1.0"
androix-paging-compose = "1.0.0-alpha14"
androidx-hilt = "1.0.0"
androidx-camera = "1.0.2"
androidx-camera-view = "1.2.0-alpha01"

datastore-preferences = "1.0.0"

google-material = "1.5.0"

constraint-layout = "1.0.0"

junit4 = "4.13.2"
retrofit2-runtime = "2.9.0"
retrofit2-koltinx-serialization = "0.8.0"
okhttp3 = "4.9.3"

kotlinx-serialization = "1.3.2"
kotlinx-coroutines = "1.6.2"

coil = "2.1.0"

google-accompanist = "0.23.1"

google-services = "20.2.0"

firebase = "30.1.0"

twyper-swipe = "0.0.4"

[libraries]
dagger-runtime = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-agp = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }

androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidx-camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidx-camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "androidx-camera-view" }

androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-animations = { module = "androidx.compose.animation:animation", version.ref = "compose" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraint-layout" }

androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-core-ktx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androix-paging" }
androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "androix-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androix-paging-compose" }

androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0-alpha03" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version = "1.0.0" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version = "1.0.0" }

google-material = { module = "com.google.android.material:material", version.ref = "google-material" }

androidx-test-ext = { module = "androidx.test.ext:junit", version.ref = "androidx-test" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

junit4 = { module = "junit:junit", version.ref = "junit4" }

retrofit2-runtime = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2-runtime" }
retrofit2-koltinx-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-koltinx-serialization" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }

kotlin-lib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines"}

coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "google-accompanist" }
google-accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "google-accompanist" }
google-accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "google-accompanist" }
google-accompanist-swipeRefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "google-accompanist" }
google-accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "google-accompanist" }
google-accompanist-pager-indicator = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "google-accompanist" }
google-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "google-accompanist" }

google-firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
google-firebase-database = { module = "com.google.firebase:firebase-database-ktx" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
google-play-services = { module = "com.google.android.gms:play-services-auth", version.ref = "google-services" }
twyper = { module = "com.github.theapache64:twyper", version.ref = "twyper-swipe" }

[bundles]
androidx-compose = [
    "androidx-compose-activity",
    "androidx-compose-ui",
    "androidx-compose-material",
    "androidx-compose-ui-toolingPreview",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-util",
    "androidx-compose-material-icons",
    "androidx-compose-runtime",
    "androidx-compose-animations",
    "androidx-compose-navigation",
    "androidx-compose-constraintlayout",
    "androidx-compose-material-icons-extended"
]

google-accompanist = [
    "google-accompanist-systemuicontroller",
    "google-accompanist-insets",
    "google-accompanist-flowlayout",
    "google-accompanist-swipeRefresh",
    "google-accompanist-pager",
    "google-accompanist-pager-indicator",
    "google-accompanist-permissions"
]

androidx-lifecycle = [
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-ktx",
    "androidx-lifecycle-livedata-ktx",
    "androidx-lifecycle-livedata-core-ktx",
]

androidx-camera = [
    "androidx-camera2",
    "androidx-camera-lifecycle",
    "androidx-camera-view"
]

androidx-test-espresso = ["androidx-test-espresso-core"]

androidx-paging = ["androidx-paging-runtime", "androidx-paging-common", "androidx-paging-compose"]

retrofit2 = ["retrofit2-runtime", "okhttp3", "retrofit2-koltinx-serialization", "kotlinx-serialization"]

kotlinx-coroutines = ["kotlinx-coroutines-android", "kotlinx-coroutines-core", "kotlinx-coroutines-play-services"]
